<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Edf.Application" />
    <InternalsVisibleTo Include="Edf.Application.Tests" />
    <InternalsVisibleTo Include="Edf.ProjectServices.Tests" />
  </ItemGroup>

</Project>
